SET "ORBITER_FOLDER=C:\Games\Orbiter2016\"
SET "VESSEL_FOLDER=%ORBITER_FOLDER%Orbitersdk\UACS\Orbiter\"

SET "LINK_PATH=Config\UACS.cfg"
mklink /h "%ORBITER_FOLDER%%LINK_PATH%" "%VESSEL_FOLDER%%LINK_PATH%"

SET "LINK_PATH=Config\Vessels\UACS"
mklink /j "%ORBITER_FOLDER%%LINK_PATH%" "%VESSEL_FOLDER%%LINK_PATH%"

SET "LINK_PATH=Images\Vessels\UACS"
mklink /j "%ORBITER_FOLDER%%LINK_PATH%" "%VESSEL_FOLDER%%LINK_PATH%"

SET "LINK_PATH=Meshes\UACS"
mklink /j "%ORBITER_FOLDER%%LINK_PATH%" "%VESSEL_FOLDER%%LINK_PATH%"

mkdir "%ORBITER_FOLDER%Orbitersdk\include\UACS"

SET "LINK_PATH=Common.h"
mklink /h "%ORBITER_FOLDER%Orbitersdk\include\UACS\%LINK_PATH%" "%VESSEL_FOLDER%..\Sources\API\%LINK_PATH%"

SET "LINK_PATH=Astronaut.h"
mklink /h "%ORBITER_FOLDER%Orbitersdk\include\UACS\%LINK_PATH%" "%VESSEL_FOLDER%..\Sources\API\%LINK_PATH%"

SET "LINK_PATH=Cargo.h"
mklink /h "%ORBITER_FOLDER%Orbitersdk\include\UACS\%LINK_PATH%" "%VESSEL_FOLDER%..\Sources\API\%LINK_PATH%"

SET "LINK_PATH=Module.h"
mklink /h "%ORBITER_FOLDER%Orbitersdk\include\UACS\%LINK_PATH%" "%VESSEL_FOLDER%..\Sources\API\%LINK_PATH%"

SET "LINK_PATH=Scenarios\UACS"
mklink /j "%ORBITER_FOLDER%%LINK_PATH%" "%VESSEL_FOLDER%%LINK_PATH%"

SET "LINK_PATH=Textures\UACS"
mklink /j "%ORBITER_FOLDER%%LINK_PATH%" "%VESSEL_FOLDER%%LINK_PATH%"